version: '3.1'

services:
    drupal:
        image: drupal:8
        ports: 
            - 8080:80
        volumes:
            - drupal_modules:/var/www/html/modules
            - drupal_profiles:/var/www/html/profiles
            - drupal_themes:/var/www/html/themes

    postgres:
        image: postgres
        secrets:
            - psql_password
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
        volumes:
            - drupal_data:/var/lib/postgresql/data

volumes:
    drupal_modules:
    drupal_profiles:
    drupal_themes:
    drupal_data:

secrets:
    psql_password:
        external: true